### ISSUE TITLE
Error with push fopen(php://stderr): failed to open stream: operation failed

### ISSUE THREAD

**Issue by ejeanneaubc** [Vinelab/cdn#111]
Hi !

I have an error when in push with the console but not each times.

I upload on S3, a lot of files has been uploaded but i have this error : 

```
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'fopen(php://stderr): failed to open stream: operation failed' in /private/var/www/bc_admin/vendor/symfony/console/Output/ConsoleOutput.php:154
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'fopen(php://std...', '/private/var/ww...', 154, Array)
#1 /private/var/www/bc_admin/vendor/symfony/console/Output/ConsoleOutput.php(154): fopen('php://stderr', 'w')
#2 /private/var/www/bc_admin/vendor/symfony/console/Output/ConsoleOutput.php(48): Symfony\Component\Console\Output\ConsoleOutput->openErrorStream()
#3 /private/var/www/bc_admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(96): Symfony\Component\Console\Output\ConsoleOutput->__construct()
#4 /private/var/www/bc_admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(82): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole(Object(ErrorException))
#5 [internal function]: Illumi in /private/var/www/bc_admin/vendor/symfony/console/Output/ConsoleOutput.php on line 154
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'include(/private/var/www/bc_admin/vendor/symfony/debug/Exception/FatalErrorException.php): failed to open stream: Too many open files' in /private/var/www/bc_admin/vendor/composer/ClassLoader.php:412
Stack trace:
#0 /private/var/www/bc_admin/vendor/composer/ClassLoader.php(412): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'include(/privat...', '/private/var/ww...', 412, Array)
#1 /private/var/www/bc_admin/vendor/composer/ClassLoader.php(412): Composer\Autoload\includeFile()
#2 /private/var/www/bc_admin/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/private/var/ww...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#4 /private/var/www/bc_admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(131): spl_autoload_call('Symfony\\Compone...')
#5 /private/var/www/bc_admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.ph in /private/var/www/bc_admin/vendor/composer/ClassLoader.php on line 412
```

And when i change in ConsoleOutput i can see this error when i launch push : 

```
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'proc_open(): unable to create pipe Too many open files' in /private/var/www/bc_admin/vendor/symfony/console/Application.php:901
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'proc_open(): un...', '/private/var/ww...', 901, Array)
#1 /private/var/www/bc_admin/vendor/symfony/console/Application.php(901): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 /private/var/www/bc_admin/vendor/symfony/console/Application.php(704): Symfony\Component\Console\Application->getSttyColumns()
#3 /private/var/www/bc_admin/vendor/symfony/console/Application.php(665): Symfony\Component\Console\Application->getTerminalDimensions()
#4 /private/var/www/bc_admin/vendor/symfony/console/Application.php(598): Symfony\Component\Console\Application->getTerminalWidth()
#5 /private/var/www/bc_admin/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(142): Symfony\Component\Console\Application->ren in /private/var/www/bc_admin/vendor/symfony/console/Application.php on line 901
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'include(/private/var/www/bc_admin/vendor/symfony/debug/Exception/FatalErrorException.php): failed to open stream: Too many open files' in /private/var/www/bc_admin/vendor/composer/ClassLoader.php:412
Stack trace:
#0 /private/var/www/bc_admin/vendor/composer/ClassLoader.php(412): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'include(/privat...', '/private/var/ww...', 412, Array)
#1 /private/var/www/bc_admin/vendor/composer/ClassLoader.php(412): Composer\Autoload\includeFile()
#2 /private/var/www/bc_admin/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/private/var/ww...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#4 /private/var/www/bc_admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(131): spl_autoload_call('Symfony\\Compone...')
#5 /private/var/www/bc_admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.ph in /private/var/www/bc_admin/vendor/composer/ClassLoader.php on line 412
```

I use laravel 5.3 on PHP 5.6

Can you help me please ?

Thank's a lot !

Bye

**Comment by ejeanneaubc** [comment]
Hi,

I have found the fix, if i can help anyone. I'am on OSX. I've type this command in Terminal which save my life :) 

> ulimit -Sn 4096

Enjoy !
